# Singular Value Decomposition (SVD)

<img src="../figs/SVD.png" width="33%">

Unique matrix decomposition that exists for every complex-valued matrix: $X = U \Sigma V^*~,$ \
where $U \in \mathbb{C}^{n \times n}$ and $V \in \mathbb{C}^{m \times m}$ are unitary matrices (i.e. $UU^*=U^*U=I$) with orthogonal columns. \
$\Sigma \in \mathbb{R}^{n \times m}$ (singular values) is a matrix with real, non-negative entries on the diagonal and elsewhere zero.

- Optimal approximation with Eckart-Young theorem: "Find SVD at rank $r$ with lowest Frobenius norm"
- Error can be exactly quantified as $||X - \tilde{X}||^2_F = \sum_{k=r+1}^m \sigma_k^2$.

#### Scaling
- computation time: $\mathcal{O}(m n^2 + m^3)$
- memory usage: $\mathcal{O}(mn)$

In [1]:
import numpy as np

In [2]:
X = np.random.rand(5,3)
print("Original matrix:", X)
U, S, V_T = np.linalg.svd(X, full_matrices=True)
U_hat, S_hat, V_T = np.linalg.svd(X, full_matrices=False)

print("\nSingular values", S)

# Truncated SVD of rank r
r = 2
X_tilde = U_hat[:, :r] @ np.diag(S_hat[:r]) @ V_T[:r, :]
print(f"\nROM to rank {r}:", X_tilde)

# Trunction error
eps = np.linalg.norm(X - X_tilde, 'fro')
eps_rel = eps / np.linalg.norm(X, 'fro') * 100
print(f"\nTruncation error: {eps:.2f}, {eps_rel:.2f}%")

Original matrix: [[0.07213241 0.19455004 0.68187768]
 [0.21569743 0.93885505 0.26032407]
 [0.37473935 0.74719484 0.74534926]
 [0.42743681 0.10559212 0.69565441]
 [0.69829747 0.38470504 0.44280127]]

Singular values [1.87105213 0.73843637 0.47051135]

ROM to rank 2: [[0.32133867 0.16781982 0.54254625]
 [0.23877192 0.93638004 0.2474231 ]
 [0.46697661 0.73730134 0.69377933]
 [0.40691729 0.10779307 0.70712689]
 [0.38905854 0.41787444 0.61569702]]

Truncation error: 0.47, 22.78%


In [9]:
# Method of snapshots - Eigendecompostion of X.T * X
S2, V = np.linalg.eig(X.T @ X)

# Method of snapshots
# 1) Sort eigenvalues in descending order
idx_sort = np.argsort(S2)[::-1]
S2 = S2[idx_sort]
V = V[:, idx_sort]
print("Singular values:", np.sqrt(S2))

# 2) Sort V vector in same order

# 2) Compute first m columns of U
S_mos = np.diag(np.sqrt(S2))
S_mos_inv = np.diag(1 / np.sqrt(S2))
U_mos = X @ V @ S_mos_inv
X_mos = U_mos @ S_mos @ V.T
print("\nReconstructed matrix:", X_mos)

eps_mos = np.linalg.norm(X - X_mos, 'fro')
print(f"\nReconstruction error: {eps_mos:.2f}")


Singular values: [1.87105213 0.73843637 0.47051135]

Reconstructed matrix: [[0.07213241 0.19455004 0.68187768]
 [0.21569743 0.93885505 0.26032407]
 [0.37473935 0.74719484 0.74534926]
 [0.42743681 0.10559212 0.69565441]
 [0.69829747 0.38470504 0.44280127]]

Reconstruction error: 0.00
